Repository ursais/osi-addons, pull requests merged in 2019-07, with the labels that each got.

#112 [IMP] connector_voicent_helpdesk_ticket: Raise RetryableJobError
  connector_voicent_helpdesk_ticket/README.rst
  connector_voicent_helpdesk_ticket/__manifest__.py
  connector_voicent_helpdesk_ticket/models/backend_voicent_call_line.py
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
  connector_voicent_helpdesk_ticket/security/ir.model.access.csv
  connector_voicent_helpdesk_ticket/tests/test_helpdesk_ticket.py
  connector_voicent_helpdesk_ticket/view/backend_voicent.xml
  connector_voicent_helpdesk_ticket/view/backend_voicent_call_line.xml
Labels: enhancement

#132 [FIX] connector_voicent_helpdesk_ticket: Contact list is empty
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: bug

#129 [FIX] helpdesk_stock: set the procurement group
  helpdesk_stock/models/stock.py
  helpdesk_stock/models/stock_request.py
Labels: bug, needs review

#131 [IMP] helpdesk_fieldservice: Default Search Open Tickets
  helpdesk_fieldservice/models/fsm_location.py
Labels: enhancement

#130 [FIX] fieldservice_helpdesk_stock: license and procurement group
  fieldservice_helpdesk_stock/README.rst
  fieldservice_helpdesk_stock/__init__.py
  fieldservice_helpdesk_stock/__manifest__.py
  fieldservice_helpdesk_stock/models/__init__.py
  fieldservice_helpdesk_stock/models/fsm_order.py
  fieldservice_helpdesk_stock/models/stock_request.py
  fieldservice_helpdesk_stock/views/helpdesk_views.xml
Labels: bug, needs review

#134 [FIX] connector_voicent_helpdesk_ticket: security
  connector_voicent_helpdesk_ticket/security/ir.model.access.csv
Labels: bug

#133 [FIX] helpdesk_ticket: KeyError: 'ticket_id'
  helpdesk_stock/models/helpdesk_ticket.py
  helpdesk_stock/models/stock_request.py
  helpdesk_stock/views/stock_request.xml
Labels: bug

#136 [FIX] connector_voicent_helpdesk_service: Rights on contact info
  connector_voicent_helpdesk_ticket/security/ir.model.access.csv
Labels: bug

#137 [FIX] helpdesk_stock: AttributeError: 'stock.request' object has no a…
  helpdesk_stock/models/stock.py
Labels: bug, needs review

#138 [FIX] connector_voicent_helpdesk_ticket: TypeError: unsupported opera…
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: bug

#142 [IMP] helpdesk_stock: Views
  helpdesk_stock/views/helpdesk_views.xml
Labels: enhancement

#143 [FIX] fieldservice_helpdesk_stock: Set the partner on the picking
  fieldservice_helpdesk_stock/models/stock_request.py
Labels: bug

#144 [FIX] helpdesk_stock: prepare_order_values()
  helpdesk_stock/models/stock_request.py
Labels: bug

#145 [IMP] helpdesk_stock: Create a new order if direction is different
  helpdesk_stock/models/stock_request.py
Labels: enhancement

#117 [ADD] osi_analytic_segments
  osi_analytic_segments/README.rst
  osi_analytic_segments/__init__.py
  osi_analytic_segments/__manifest__.py
  osi_analytic_segments/i18n/en_US.po
  osi_analytic_segments/models/__init__.py
  osi_analytic_segments/models/account_analytic_line.py
  osi_analytic_segments/models/account_invoice.py
  osi_analytic_segments/models/account_move.py
  osi_analytic_segments/models/analytic_seg.py
  osi_analytic_segments/security/ir.model.access.csv
  osi_analytic_segments/static/description/icon.png
  osi_analytic_segments/views/account_analytic_line_view.xml
  osi_analytic_segments/views/account_invoice_view.xml
  osi_analytic_segments/views/account_move_view.xml
  osi_analytic_segments/views/analytic_segment.xml
Labels: enhancement, needs review

#127 [ADD] osi_vendor_reference
  osi_vendor_reference/README.rst
  osi_vendor_reference/__init__.py
  osi_vendor_reference/__manifest__.py
  osi_vendor_reference/models/__init__.py
  osi_vendor_reference/models/account_invoice.py
  osi_vendor_reference/static/description/icon.png
Labels: enhancement, needs review

#126 [ADD] osi_analytic_sales_simple
  osi_analytic_sales_simple/README.rst
  osi_analytic_sales_simple/__init__.py
  osi_analytic_sales_simple/__manifest__.py
  osi_analytic_sales_simple/models/__init__.py
  osi_analytic_sales_simple/models/account_invoice.py
  osi_analytic_sales_simple/models/sale_order_line.py
  osi_analytic_sales_simple/static/description/icon.png
  osi_analytic_sales_simple/views/sale_order_view.xml
  osi_analytic_sales_simple/wizard/__init__.py
  osi_analytic_sales_simple/wizard/sale_make_invoice_advance.py
Labels: enhancement, needs review

#146 [FIX] connector_voicent_helpdesk_ticket: Use self
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: bug

#124 [ADD] osi_analytic_segments_purchase
  osi_analytic_segments_purchase/README.rst
  osi_analytic_segments_purchase/__init__.py
  osi_analytic_segments_purchase/__manifest__.py
  osi_analytic_segments_purchase/i18n/en_US.po
  osi_analytic_segments_purchase/models/__init__.py
  osi_analytic_segments_purchase/models/account_invoice.py
  osi_analytic_segments_purchase/models/purchase_order.py
  osi_analytic_segments_purchase/static/description/icon.png
  osi_analytic_segments_purchase/views/purchase_order_view.xml
Labels: enhancement, needs review

#125 [ADD] osi_analytic_segments_expenses
  osi_analytic_segments_expenses/README.rst
  osi_analytic_segments_expenses/__init__.py
  osi_analytic_segments_expenses/__manifest__.py
  osi_analytic_segments_expenses/i18n/en_US.po
  osi_analytic_segments_expenses/models/__init__.py
  osi_analytic_segments_expenses/models/hr_expense.py
  osi_analytic_segments_expenses/static/description/icon.png
  osi_analytic_segments_expenses/views/hr_expense_views.xml
Labels: enhancement, needs review

#121 [ADD] osi_payment_method
  osi_payment_method/README.rst
  osi_payment_method/__init__.py
  osi_payment_method/__manifest__.py
  osi_payment_method/models/__init__.py
  osi_payment_method/models/account_invoice.py
  osi_payment_method/models/custom_payment_method.py
  osi_payment_method/models/purchase.py
  osi_payment_method/models/res_partner.py
  osi_payment_method/models/sale.py
  osi_payment_method/security/ir.model.access.csv
  osi_payment_method/static/description/icon.png
  osi_payment_method/views/account_invoice_views.xml
  osi_payment_method/views/payment_views.xml
  osi_payment_method/views/purchase_views.xml
  osi_payment_method/views/res_partner.xml
  osi_payment_method/views/sale_views.xml
Labels: enhancement, needs review

#122 [ADD] osi_analytic_segments_defaults
  osi_analytic_segments_defaults/README.rst
  osi_analytic_segments_defaults/__init__.py
  osi_analytic_segments_defaults/__manifest__.py
  osi_analytic_segments_defaults/i18n/en_US.po
  osi_analytic_segments_defaults/models/__init__.py
  osi_analytic_segments_defaults/models/account_analytic_default.py
  osi_analytic_segments_defaults/models/purchase_order.py
  osi_analytic_segments_defaults/models/sale_order_line.py
  osi_analytic_segments_defaults/static/description/icon.png
  osi_analytic_segments_defaults/views/account_analytic_default_view.xml
Labels: enhancement, needs review

#123 [ADD] osi_analytic_segments_sales
  osi_analytic_segments_sales/README.rst
  osi_analytic_segments_sales/__init__.py
  osi_analytic_segments_sales/__manifest__.py
  osi_analytic_segments_sales/i18n/en_US.po
  osi_analytic_segments_sales/models/__init__.py
  osi_analytic_segments_sales/models/account_invoice.py
  osi_analytic_segments_sales/models/sale_order.py
  osi_analytic_segments_sales/static/description/icon.png
  osi_analytic_segments_sales/views/sale_order_view.xml
  osi_analytic_segments_sales/wizard/__init__.py
  osi_analytic_segments_sales/wizard/sale_make_invoice_advance.py
Labels: enhancement, work in progress

#147 [IMP] connector_voicent_helpdesk_ticket: Add call_count
  connector_voicent_helpdesk_ticket/README.rst
  connector_voicent_helpdesk_ticket/__manifest__.py
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: enhancement, needs review

#148 [FIX] helpdesk_stock: default ticket
  helpdesk_stock/views/stock_request_order.xml
Labels: bug

#149 [FIX] helpdesk_fieldservice: Context on Contact Smart Button
  helpdesk_fieldservice/__manifest__.py
  helpdesk_fieldservice/views/res_partner.xml
Labels: bug

#150 [IMP] connector_voicent_helpdesk_ticket: Use Voicent-Python lib
  connector_voicent_helpdesk_ticket/README.rst
  connector_voicent_helpdesk_ticket/__manifest__.py
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
  requirements.txt
Labels: enhancement, needs review

#153 [FIX] helpdesk_stock: Key (fsm_order_id) is not present in table "fsm…
  helpdesk_stock/models/stock_request.py
  helpdesk_stock/models/stock_request_order.py
  helpdesk_stock/views/stock_request_order.xml
Labels: bug

#154 [FIX] helpdesk_stock: Expected singleton: procurement.group
  helpdesk_stock/models/stock_request.py
Labels: bug

#155 [FIX] fieldservice_helpdesk_stock: Expected singleton: procurement.group
  fieldservice_helpdesk_stock/models/stock_request.py
Labels: bug

#156 [FIX] agreement_sale_subscription: Expected singleton: agreement()
  agreement_sale_subscription/models/sale_order.py
Labels: bug

#157 [IMP] fieldservice_helpdesk_stock: Use the shipping address
  fieldservice_helpdesk_stock/models/stock_request.py
Labels: enhancement

#159 [FIX] osi_payment_method: Onchange Partner ID
  osi_payment_method/models/account_invoice.py
Labels: bug

#160 [FIX] fieldservice_helpdesk_stock: procurement.group
  fieldservice_helpdesk_stock/models/stock_request.py
Labels: bug

#162 [FIX] helpdesk_fieldservice: Contact Context
  helpdesk_fieldservice/views/res_partner.xml
Labels: bug, needs review

#163 [ADD] Credit Card Reconciliation
  .travis.yml
  oca_dependencies.txt
  osi_credit_card_reconciliation/README.rst
  osi_credit_card_reconciliation/__init__.py
  osi_credit_card_reconciliation/__manifest__.py
  osi_credit_card_reconciliation/models/__init__.py
  osi_credit_card_reconciliation/models/account_move_line.py
  osi_credit_card_reconciliation/models/cc_rec_statement.py
  osi_credit_card_reconciliation/models/cc_rec_statement_line.py
  osi_credit_card_reconciliation/report/cc_rec_statement_detail.xml
  osi_credit_card_reconciliation/report/cc_rec_statement_summary.xml
  osi_credit_card_reconciliation/report/cc_rec_statement_view.xml
  osi_credit_card_reconciliation/security/credit_card_reconciliation_security.xml
  osi_credit_card_reconciliation/security/ir.model.access.csv
  osi_credit_card_reconciliation/static/description/icon.png
  osi_credit_card_reconciliation/views/account_move_line_view.xml
  osi_credit_card_reconciliation/views/cc_rec_statement_view.xml
Labels: enhancement, needs review

#161 [FIX] osi_payment_method: Use account.payment.method
  osi_payment_method/README.rst
  osi_payment_method/__init__.py
  osi_payment_method/__manifest__.py
  osi_payment_method/models/__init__.py
  osi_payment_method/models/account_invoice.py
  osi_payment_method/models/custom_payment_method.py
  osi_payment_method/models/purchase.py
  osi_payment_method/models/res_partner.py
  osi_payment_method/models/sale.py
  osi_payment_method/security/ir.model.access.csv
  osi_payment_method/views/account_invoice_views.xml
  osi_payment_method/views/payment_views.xml
  osi_payment_method/views/purchase_views.xml
  osi_payment_method/views/res_partner_views.xml
  osi_payment_method/views/sale_views.xml
Labels: bug

#164 [FIX] osi_credit_card_reconciliation
  osi_credit_card_reconciliation/models/cc_rec_statement.py
  osi_credit_card_reconciliation/models/cc_rec_statement_line.py
Labels: bug

#165 [IMP] connector_voicent_helpdesk_ticket: Implement identity key to av…
  connector_voicent_helpdesk_ticket/__manifest__.py
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: enhancement

#168 [ADD] osi_account_bank_statement
  osi_account_bank_statement/README.rst
  osi_account_bank_statement/__init__.py
  osi_account_bank_statement/__manifest__.py
  osi_account_bank_statement/models/__init__.py
  osi_account_bank_statement/models/account.py
  osi_account_bank_statement/static/description/icon.png
Labels: enhancement, needs fixing

#167 [FIX] connector_voicent_helpdesk_ticket
  connector_voicent_helpdesk_ticket/README.rst
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: bug

#169 [IMP] helpdesk_fieldservice: Remove 'Add a line'
  helpdesk_fieldservice/views/helpdesk_ticket_views.xml
Labels: enhancement

#151 [ADD] sale_subscription_suspend
  sale_subscription_suspend/README.rst
  sale_subscription_suspend/__init__.py
  sale_subscription_suspend/__manifest__.py
  sale_subscription_suspend/data/sale_subscription_data.xml
  sale_subscription_suspend/models/__init__.py
  sale_subscription_suspend/models/sale_subscription.py
  sale_subscription_suspend/static/description/icon.png
  sale_subscription_suspend/views/sale_subscription.xml
Labels: enhancement, needs review
