Repository ursais/osi-addons, pull requests merged in 2019-06, with the labels that each got.

#105 [IMP] helpdesk_fieldservice: Create Order Button (PM #550)
  helpdesk_fieldservice/models/helpdesk_ticket.py
  helpdesk_fieldservice/views/helpdesk_ticket_views.xml
Labels: needs fixing

#104 [ADD] helpdesk_team_assigned_tickets
  .travis.yml
  helpdesk_team_assigned_tickets/README.rst
  helpdesk_team_assigned_tickets/__init__.py
  helpdesk_team_assigned_tickets/__manifest__.py
  helpdesk_team_assigned_tickets/models/__init__.py
  helpdesk_team_assigned_tickets/models/helpdesk.py
  helpdesk_team_assigned_tickets/static/description/icon.png
  helpdesk_team_assigned_tickets/tests/__init__.py
  helpdesk_team_assigned_tickets/tests/common.py
  helpdesk_team_assigned_tickets/tests/test_helpdesk_team.py
  helpdesk_team_assigned_tickets/views/helpdesk_team.xml
Labels: work in progress

#106 [IMP] Fix Ticket Email Repeat
  helpdesk_stage_server_action/data/base_automation.xml
Labels: bug

#107 [FIX] helpdesk_stage_server_action: set action_id on stages
  helpdesk_stage_server_action/__manifest__.py
  helpdesk_stage_server_action/data/base_automation.xml
  helpdesk_stage_server_action/data/helpdesk_stage.xml
Labels: bug

#109 [IMP] helpdesk_fieldservice: Add View Order Button
  helpdesk_fieldservice/models/fsm_order.py
  helpdesk_fieldservice/static/src/scss/helpdesk_column.scss
  helpdesk_fieldservice/views/helpdesk_ticket_views.xml
Labels: enhancement

#97 [ADD] connector_voicent_helpdesk_ticket
  .travis.yml
  connector_voicent_helpdesk_ticket/README.rst
  connector_voicent_helpdesk_ticket/__init__.py
  connector_voicent_helpdesk_ticket/__manifest__.py
  connector_voicent_helpdesk_ticket/models/__init__.py
  connector_voicent_helpdesk_ticket/models/backend_voicent_call_line.py
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
  connector_voicent_helpdesk_ticket/static/description/icon.png
  connector_voicent_helpdesk_ticket/tests/__init__.py
  connector_voicent_helpdesk_ticket/tests/test_helpdesk_ticket.py
  connector_voicent_helpdesk_ticket/view/backend_voicent_call_line_view.xml
  oca_dependencies.txt
Labels: enhancement

#111 [FIX] helpdesk_stock: Add ticket to stock request
  helpdesk_stock/__manifest__.py
  helpdesk_stock/models/__init__.py
  helpdesk_stock/models/stock.py
  helpdesk_stock/models/stock_request.py
  helpdesk_stock/views/stock_request.xml
Labels: bug

#113 [FIX] connector_voicent_helpdesk_ticket: TypeError: lstat: path shoul…
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: bug

#114 [FIX] helpdesk_stage_server_action: Remove Noupdate
  helpdesk_stage_server_action/data/base_automation.xml
  helpdesk_stage_server_action/data/helpdesk_stage.xml
  helpdesk_stage_server_action/data/ir_servers_action.xml
Labels: bug

#115 [FIX] helpdesk_team_assigned_tickets: Overwrite Active ID
  helpdesk_team_assigned_tickets/views/helpdesk_team.xml
Labels: bug
