Repository ursais/osi-addons, pull requests merged in 2019-08, with the labels that each got.

#166 [FIX] osi_analytic_*
  osi_analytic_sales_simple/__manifest__.py
  osi_analytic_sales_simple/models/sale_order_line.py
  osi_analytic_sales_simple/wizard/sale_make_invoice_advance.py
  osi_analytic_segments/__init__.py
  osi_analytic_segments/__manifest__.py
  osi_analytic_segments/models/__init__.py
  osi_analytic_segments/models/account_analytic_line.py
  osi_analytic_segments/models/account_invoice.py
  osi_analytic_segments/models/account_move_line.py
  osi_analytic_segments/models/analytic_seg.py
  osi_analytic_segments/views/account_analytic_line_view.xml
  osi_analytic_segments/views/account_invoice_view.xml
  osi_analytic_segments/views/account_move_view.xml
  osi_analytic_segments/views/analytic_segment.xml
  osi_analytic_segments_sales/__manifest__.py
  osi_analytic_segments_sales/models/sale_order.py
  osi_analytic_segments_sales/wizard/sale_make_invoice_advance.py
Labels: bug

#171 [IMP] helpdesk_fieldservice: Filter Tickets with Closed Orders
  helpdesk_fieldservice/models/helpdesk_ticket.py
  helpdesk_fieldservice/views/helpdesk_ticket_views.xml
Labels: enhancement, needs review

#175 [FIX] helpdesk_team_assigned_tickets
  helpdesk_team_assigned_tickets/views/helpdesk_team.xml
Labels: bug

#174 [FIX] osi_account_bank_statement: AttributeError: 'account.journal' o…
  osi_account_bank_statement/README.rst
  osi_account_bank_statement/__init__.py
  osi_account_bank_statement/__manifest__.py
  osi_account_bank_statement/models/__init__.py
  osi_account_bank_statement/models/account.py
Labels: bug, needs review

#179 [FIX] connector_voicent_helpdesk_ticket: TypeError: generate_identity…
  connector_voicent_helpdesk_ticket/README.rst
  connector_voicent_helpdesk_ticket/__manifest__.py
  connector_voicent_helpdesk_ticket/models/helpdesk_ticket.py
Labels: bug

#178 [FIX] osi_payment_method: Permission
  osi_payment_method/__manifest__.py
  osi_payment_method/security/ir.model.access.csv
Labels: bug, needs review

#177 [FIX] helpdesk_stock: depends on stock_request_direction
  helpdesk_stock/__manifest__.py
  helpdesk_stock/views/stock_request.xml
  helpdesk_stock/views/stock_request_order.xml
Labels: bug, needs review

#158 [ADD] sale_subscription_brand
  .travis.yml
  oca_dependencies.txt
  sale_subscription_brand/README.rst
  sale_subscription_brand/__init__.py
  sale_subscription_brand/__manifest__.py
  sale_subscription_brand/models/__init__.py
  sale_subscription_brand/models/sale_order.py
  sale_subscription_brand/models/sale_subscription.py
  sale_subscription_brand/static/description/icon.png
  sale_subscription_brand/views/sale_subscription_views.xml
Labels: enhancement, needs review

#181 [IMP] helpdesk_stock: Stock Request Order Search View
  helpdesk_stock/__manifest__.py
  helpdesk_stock/views/stock_request.xml
  helpdesk_stock/views/stock_request_order.xml
Labels: enhancement, needs review

#182 [FIX] osi_credit_card_reconciliation: ValueError: Invalid field 'supp…
  osi_credit_card_reconciliation/__manifest__.py
  osi_credit_card_reconciliation/models/cc_rec_statement.py
Labels: bug, needs review

#180 [ADD] agreement sale subscription suspension
  .travis.yml
  agreement_sale_subscription_suspension/__init__.py
  agreement_sale_subscription_suspension/__manifest__.py
  agreement_sale_subscription_suspension/models/__init__.py
  agreement_sale_subscription_suspension/models/sale_subscription.py
Labels: needs review

#185 [FIX] agreement_sale_subscription: Agreement Not Set on Subscription From Sale Order
  agreement_sale_subscription/README.rst
  agreement_sale_subscription/__manifest__.py
  agreement_sale_subscription/models/sale_order.py
Labels: bug, needs fixing
