Repository ursais/osi-addons, pull requests merged in 2019-01, with the labels that each got.

#50 [FIX] agreement_sale_subscription
  agreement_sale_subscription/views/agreement.xml
  agreement_sale_subscription/views/subscription.xml
Labels: bug

#57 [FIX]Added carry over for agreement and service profile
  .travis.yml
  fieldservice_helpdesk_stock/views/fsm_order_view.xml
  fieldservice_helpdesk_stock/views/helpdesk_ticket_view.xml
  helpdesk_fieldservice_agreement/README.rst
  helpdesk_fieldservice_agreement/__init__.py
  helpdesk_fieldservice_agreement/__manifest__.py
  helpdesk_fieldservice_agreement/static/description/icon.png
  helpdesk_fieldservice_agreement/views/helpdesk_ticket_views.xml
Labels: needs review

#59 [IMP] helpdesk_fieldservice
  helpdesk_fieldservice/views/fsm_order_views.xml
Labels: enhancement
