Repository ursais/osi-addons, pull requests merged in 2019-11, with the labels that each got.

#212 [FIX] helpdesk_fieldservice: CSS download failure
  helpdesk_fieldservice/__manifest__.py
  helpdesk_fieldservice/models/helpdesk_ticket.py
  helpdesk_fieldservice/views/helpdesk_ticket_views.xml
Labels: bug, needs review

#213 [FIX] osi_analytic_segments: KeyError: 0
  osi_analytic_segments/__manifest__.py
  osi_analytic_segments/models/account_move_line.py
Labels: bug, needs review

#214 [IMP] helpdesk_fieldservice (Close Ticket Wizard)
  fieldservice_helpdesk_stock/views/fsm_location.xml
  helpdesk_fieldservice/__init__.py
  helpdesk_fieldservice/__manifest__.py
  helpdesk_fieldservice/models/fsm_order.py
  helpdesk_fieldservice/wizard/__init__.py
  helpdesk_fieldservice/wizard/fsm_order_close_wizard.py
  helpdesk_fieldservice/wizard/fsm_order_close_wizard.xml
Labels: enhancement, needs review

#217 [ADD] osi_analytic_segments_stock
  osi_analytic_segments_stock/README.rst
  osi_analytic_segments_stock/__init__.py
  osi_analytic_segments_stock/__manifest__.py
  osi_analytic_segments_stock/models/__init__.py
  osi_analytic_segments_stock/models/stock_move.py
  osi_analytic_segments_stock/models/stock_move_line.py
  osi_analytic_segments_stock/models/stock_scrap.py
  osi_analytic_segments_stock/static/description/icon.png
  osi_analytic_segments_stock/views/stock_move.xml
  osi_analytic_segments_stock/views/stock_scrap.xml
Labels: enhancement, needs review

#218 [FIX] fieldservice_agreement_helpdesk: Ticket -> FSO: Agreement Context
  fieldservice_agreement_helpdesk/models/__init__.py
  fieldservice_agreement_helpdesk/models/helpdesk_ticket.py
  fieldservice_agreement_helpdesk/views/helpdesk_ticket.xml
Labels: bug
