Repository ursais/osi-addons, pull requests merged in 2019-10, with the labels that each got.

#195 [FIX] sale_subscription_financial_risk
  sale_subscription_financial_risk/models/account_invoice.py
Labels: bug, needs review

#205 [FIX] osi_scrap_reason_code
  README.md
  osi_scrap_reason_code/README.rst
  osi_scrap_reason_code/__init__.py
  osi_scrap_reason_code/__manifest__.py
  osi_scrap_reason_code/models/__init__.py
  osi_scrap_reason_code/models/reason_code.py
  osi_scrap_reason_code/models/stock_move.py
  osi_scrap_reason_code/models/stock_scrap.py
  osi_scrap_reason_code/security/ir.model.access.csv
  osi_scrap_reason_code/static/description/icon.png
  osi_scrap_reason_code/views/reason_code_view.xml
  osi_scrap_reason_code/views/stock_move_views.xml
  osi_scrap_reason_code/views/stock_scrap_views.xml
Labels: bug, needs review

#200 [IMP] fieldservice_account_asset: Fix Error On Install
  fieldservice_account_asset/models/res_company.py
Labels: bug, needs fixing

#206 [IMP] Add Account Voucher to Depends
  osi_credit_card_reconciliation/__manifest__.py
Labels: bug, needs review

#207 [IMP] fieldservice_helpdesk_stock: Add FSM Location to SRO's + SR's
  fieldservice_helpdesk_stock/__manifest__.py
  fieldservice_helpdesk_stock/models/__init__.py
  fieldservice_helpdesk_stock/models/fsm_location.py
  fieldservice_helpdesk_stock/models/fsm_order.py
  fieldservice_helpdesk_stock/models/helpdesk_ticket.py
  fieldservice_helpdesk_stock/models/stock_request.py
  fieldservice_helpdesk_stock/models/stock_request_order.py
  fieldservice_helpdesk_stock/tests/__init__.py
  fieldservice_helpdesk_stock/tests/test_stock_request.py
  fieldservice_helpdesk_stock/views/fsm_location.xml
  fieldservice_helpdesk_stock/views/stock_request.xml
  fieldservice_helpdesk_stock/views/stock_request_order.xml
Labels: enhancement, needs review

#211 [IMP] helpdesk_stock: Add SRO to SR list on a ticket
  helpdesk_stock/views/helpdesk_views.xml
Labels: enhancement, needs review
