Repository ursais/osi-addons, pull requests merged in 2020-08, with the labels that each got.

#276 [IMP] fieldservice_googlemaps_address_autocompletion: Address Autocomplete on Name and Street
  fieldservice_googlemaps_address_autocompletion/views/fsm_location.xml
  fieldservice_googlemaps_address_autocompletion/views/res_partner.xml
Labels: enhancement, needs review

#279 [FIX] fieldservice_mobile: Travis errors
  fieldservice_mobile/README.rst
Labels: bug

#281 [IMP] helpdesk_scope: Add sequence
  helpdesk_scope/models/helpdesk_scope.py
  helpdesk_scope/views/helpdesk_scope.xml
Labels: needs review

#282 [FIX] helpdesk_timesheet_fieldservice: Dangerous Use of "Replace"
  helpdesk_timesheet_fieldservice/views/helpdesk_ticket.xml
Labels: bug
