Repository ursais/osi-addons, pull requests merged in 2020-02, with the labels that each got.

#230 [ADD] helpdesk_motive
  .travis.yml
  helpdesk_motive/README.rst
  helpdesk_motive/__init__.py
  helpdesk_motive/__manifest__.py
  helpdesk_motive/i18n/es.po
  helpdesk_motive/i18n/pt_BR.po
  helpdesk_motive/models/__init__.py
  helpdesk_motive/models/helpdesk_ticket.py
  helpdesk_motive/models/helpdesk_ticket_motive.py
  helpdesk_motive/security/ir.model.access.csv
  helpdesk_motive/static/description/icon.png
  helpdesk_motive/views/helpdesk_ticket.xml
  helpdesk_motive/views/helpdesk_ticket_motive.xml
Labels: enhancement, needs review

#233 [ADD] osi_scrap_reason_code_analytic
  osi_analytic_segments_stock_scrap/README.rst
  osi_analytic_segments_stock_scrap/__init__.py
  osi_analytic_segments_stock_scrap/__manifest__.py
  osi_analytic_segments_stock_scrap/models/__init__.py
  osi_analytic_segments_stock_scrap/models/reason_code.py
  osi_analytic_segments_stock_scrap/models/stock_scrap.py
  osi_analytic_segments_stock_scrap/static/description/icon.png
  osi_analytic_segments_stock_scrap/views/reason_code_view.xml
  osi_analytic_segments_stock_scrap/views/stock_scrap_views.xml
Labels: enhancement, needs fixing

#232 [IMP] helpdesk_stock: Hide route_id on stock requests
  helpdesk_stock/views/helpdesk_views.xml
Labels: enhancement, needs review

#237 [UPD] Update helpdesk_phone.pot
  helpdesk_phone/i18n/es.po
  helpdesk_phone/i18n/es_CL.po
Labels: enhancement

#239 [FIX] helpdesk_motive: 'super' object has no attribute '_onchange_dom…
  helpdesk_motive/models/helpdesk_ticket.py
Labels: bug, needs review
