Repository ursais/osi-addons, pull requests merged in 2020-04, with the labels that each got.

#248 Update translation files
  helpdesk_fieldservice/i18n/es.po
Labels: enhancement

#238 [FIX] Flake8
  .travis.yml
  fieldservice_helpdesk_stock_analytic/models/stock_request.py
  osi_analytic_segments_stock_scrap/models/stock_scrap.py
  osi_bank_reconciled_report/models/account_bank_reconciled_report.py
Labels: bug

#244 [ADD] helpdesk_timesheet_fieldservice
  .travis.yml
  helpdesk_timesheet_fieldservice/README.rst
  helpdesk_timesheet_fieldservice/__init__.py
  helpdesk_timesheet_fieldservice/__manifest__.py
  helpdesk_timesheet_fieldservice/static/description/icon.png
  helpdesk_timesheet_fieldservice/views/helpdesk_ticket.xml
Labels: enhancement, needs review

#246 [ADD] helpdesk_delivery
  .travis.yml
  helpdesk_delivery/README.rst
  helpdesk_delivery/__init__.py
  helpdesk_delivery/__manifest__.py
  helpdesk_delivery/models/__init__.py
  helpdesk_delivery/models/helpdesk_ticket.py
  helpdesk_delivery/models/stock_request.py
  helpdesk_delivery/static/description/icon.png
  helpdesk_delivery/static/description/index.html
  helpdesk_delivery/views/helpdesk_ticket.xml
Labels: enhancement, needs review

#243 [IMP] helpdesk_fieldservice
  helpdesk_fieldservice/__manifest__.py
  helpdesk_fieldservice/security/ir.model.access.csv
  helpdesk_fieldservice/views/helpdesk_ticket_views.xml
  helpdesk_fieldservice/views/res_partner.xml
  helpdesk_operating_unit/README.rst
  osi_bank_reconciled_report/data/account_financial_report_data.xml
  osi_bank_reconciled_report/models/account_bank_reconciled_report.py
Labels: enhancement

#245 [ADD] account_default_payment_method
  account_default_payment_method/README.rst
  account_default_payment_method/__init__.py
  account_default_payment_method/__manifest__.py
  account_default_payment_method/models/__init__.py
  account_default_payment_method/models/account_invoice.py
  account_default_payment_method/models/account_payment.py
  account_default_payment_method/models/purchase_order.py
  account_default_payment_method/models/res_partner.py
  account_default_payment_method/models/sale_order.py
  account_default_payment_method/models/stock_rule.py
  account_default_payment_method/security/ir.model.access.csv
  account_default_payment_method/static/description/icon.png
  account_default_payment_method/views/account_invoice.xml
  account_default_payment_method/views/purchase_order.xml
  account_default_payment_method/views/res_partner.xml
  account_default_payment_method/views/sale_order.xml
Labels: enhancement, needs review

#250 [IMP] helpdesk_stock (Search by Ticket name or ID)
  helpdesk_stock/views/stock_request_order.xml
Labels: needs review

#262 [FIX] helpdesk_timesheet_fieldservice
  helpdesk_timesheet_fieldservice/views/helpdesk_ticket.xml
Labels: bug, needs review

#261 [FIX] helpdesk_delivery
  helpdesk_delivery/views/helpdesk_ticket.xml
Labels: bug, needs review

#260 [FIX] helpdesk_stock
  helpdesk_stock/__manifest__.py
  helpdesk_stock/views/helpdesk_ticket.xml
  helpdesk_stock/views/menu.xml
Labels: bug, needs review

#259 [IMP] osi_analytic_segments_stock_scrap: Default value for segment one
  osi_analytic_segments_stock_scrap/models/reason_code.py
  osi_analytic_segments_stock_scrap/models/stock_scrap.py
Labels: enhancement, needs review

#258 [IMP] osi_analytic_segments_stock: Default value for segment one
  osi_analytic_segments_stock/models/stock_move.py
  osi_analytic_segments_stock/models/stock_scrap.py
Labels: enhancement, needs review

#257 [IMP] osi_analytic_segments_sales: Default value for segment one
  osi_analytic_segments_sales/models/__init__.py
  osi_analytic_segments_sales/models/sale_order.py
  osi_analytic_segments_sales/models/sale_order_line.py
Labels: enhancement, needs review

#255 [IMP] osi_analytic_segments_purchase: Default value for segment one
  osi_analytic_segments_purchase/models/__init__.py
  osi_analytic_segments_purchase/models/account_invoice.py
  osi_analytic_segments_purchase/models/purchase_order_line.py
Labels: enhancement, needs review

#254 [IMP] osi_analytic_segments_expenses: Default value for segment one
  osi_analytic_segments_expenses/models/hr_expense.py
Labels: enhancement, needs review

#253 [IMP] osi_analytic_segments_defaults: Default value for segment one
  osi_analytic_segments_defaults/models/__init__.py
  osi_analytic_segments_defaults/models/account_analytic_default.py
  osi_analytic_segments_defaults/models/account_invoice_line.py
Labels: enhancement, needs review

#251 [IMP] helpdesk_stock: Stock request workflow adjustment
  fieldservice_helpdesk_stock/models/stock_request_order.py
  helpdesk_stock/models/stock_request.py
  helpdesk_stock/models/stock_request_order.py
Labels: enhancement, needs review
