Repository ursais/osi-addons, pull requests merged in 2022-10, with the labels that each got.

#478 [FIX] Pre-commit errors and warnings
  .eslintrc.yml
  .pre-commit-config.yaml
  osi_inventory_by_date/README.rst
  osi_inventory_by_date/__init__.py
  osi_inventory_by_date/__manifest__.py
  osi_inventory_by_date/controllers/__init__.py
  osi_inventory_by_date/controllers/main.py
  osi_inventory_by_date/report/__init__.py
  osi_inventory_by_date/report/inventory_valuation.py
  osi_inventory_by_date/security/inventory_valuation_security.xml
  osi_inventory_by_date/security/ir.model.access.csv
  osi_inventory_by_date/views/inventory_valuation_menu.xml
  osi_inventory_by_date/views/inventory_valuation_template.xml
  osi_inventory_by_date/wizard/__init__.py
  osi_inventory_by_date/wizard/inventory_valuation.py
  osi_inventory_by_date/wizard/inventory_valuation.xml
  osi_inventory_by_date/wizard/xls_format.py
  osi_stock_move_value/README.rst
  osi_stock_move_value/__init__.py
  osi_stock_move_value/__manifest__.py
  osi_stock_move_value/models/__init__.py
  osi_stock_move_value/models/stock_move.py
  osi_stock_move_value/views/stock_move_view.xml
  setup/mrp_plm_notification/odoo/addons/mrp_plm_notification
  setup/mrp_plm_notification/setup.py
  setup/osi_inventory_by_date/odoo/addons/osi_inventory_by_date
  setup/osi_inventory_by_date/setup.py
  setup/osi_stock_move_value/odoo/addons/osi_stock_move_value
  setup/osi_stock_move_value/setup.py
  setup/rma_helpdesk/odoo/addons/rma_helpdesk
  setup/rma_helpdesk/setup.py
  web_many2many_groupby/static/src/js/basic_model.js
  web_many2many_groupby/static/src/js/list_controller.js
  web_many2many_groupby/static/src/js/list_model.js
  web_many2many_groupby/static/src/js/web_groupby.js
Labels: bug, needs review

#463 [FIX] osi_account_bank_statement: Performance issue (Ticket #22880)
  osi_account_bank_statement/models/account.py
Labels: bug

#489 [FIX] Pre-commit errors and warnings
  .eslintrc.yml
  .pre-commit-config.yaml
  osi_inventory_by_date/README.rst
  osi_inventory_by_date/__init__.py
  osi_inventory_by_date/__manifest__.py
  osi_inventory_by_date/controllers/__init__.py
  osi_inventory_by_date/controllers/main.py
  osi_inventory_by_date/report/__init__.py
  osi_inventory_by_date/report/inventory_valuation.py
  osi_inventory_by_date/security/inventory_valuation_security.xml
  osi_inventory_by_date/security/ir.model.access.csv
  osi_inventory_by_date/views/inventory_valuation_menu.xml
  osi_inventory_by_date/views/inventory_valuation_template.xml
  osi_inventory_by_date/wizard/__init__.py
  osi_inventory_by_date/wizard/inventory_valuation.py
  osi_inventory_by_date/wizard/inventory_valuation.xml
  osi_inventory_by_date/wizard/xls_format.py
  osi_stock_move_value/README.rst
  osi_stock_move_value/__init__.py
  osi_stock_move_value/__manifest__.py
  osi_stock_move_value/models/__init__.py
  osi_stock_move_value/models/stock_move.py
  osi_stock_move_value/views/stock_move_view.xml
  setup/mrp_plm_notification/odoo/addons/mrp_plm_notification
  setup/mrp_plm_notification/setup.py
  setup/osi_inventory_by_date/odoo/addons/osi_inventory_by_date
  setup/osi_inventory_by_date/setup.py
  setup/osi_stock_move_value/odoo/addons/osi_stock_move_value
  setup/osi_stock_move_value/setup.py
  setup/rma_helpdesk/odoo/addons/rma_helpdesk
  setup/rma_helpdesk/setup.py
  web_many2many_groupby/static/src/js/basic_model.js
  web_many2many_groupby/static/src/js/list_controller.js
  web_many2many_groupby/static/src/js/list_model.js
  web_many2many_groupby/static/src/js/web_groupby.js
Labels: bug

#493 [FIX] pre-commit errors
  advance_check_void/__manifest__.py
  advance_check_void/data/payment_methods_data.xml
  advance_check_void/models/__init__.py
  advance_check_void/models/account_payment.py
  advance_check_void/models/payment_check_history.py
  advance_check_void/models/payment_check_void.py
  advance_check_void/views/account_payment_view.xml
  advance_check_void/views/payment_check_history_view.xml
  advance_check_void/wizard/__init__.py
  advance_check_void/wizard/account_move_reversal.py
  advance_check_void/wizard/account_move_reversal_view.xml
  advance_check_void/wizard/account_payment_register.py
  advance_check_void/wizard/simple_void_check.py
  osi_inventory_by_date/README.rst
  osi_inventory_by_date/__init__.py
  osi_inventory_by_date/__manifest__.py
  osi_inventory_by_date/controllers/__init__.py
  osi_inventory_by_date/controllers/main.py
  osi_inventory_by_date/report/__init__.py
  osi_inventory_by_date/report/inventory_valuation.py
  osi_inventory_by_date/security/inventory_valuation_security.xml
  osi_inventory_by_date/security/ir.model.access.csv
  osi_inventory_by_date/views/inventory_valuation_menu.xml
  osi_inventory_by_date/views/inventory_valuation_template.xml
  osi_inventory_by_date/wizard/__init__.py
  osi_inventory_by_date/wizard/inventory_valuation.py
  osi_inventory_by_date/wizard/inventory_valuation.xml
  osi_inventory_by_date/wizard/inventory_valuation_success_box.py
  osi_inventory_by_date/wizard/xls_format.py
  osi_stock_move_value/README.rst
  osi_stock_move_value/__init__.py
  osi_stock_move_value/__manifest__.py
  osi_stock_move_value/models/__init__.py
  osi_stock_move_value/models/stock_move.py
  osi_stock_move_value/views/stock_move_view.xml
  setup/advance_check_void/odoo/addons/advance_check_void
  setup/advance_check_void/setup.py
  setup/osi_inventory_by_date/odoo/addons/osi_inventory_by_date
  setup/osi_inventory_by_date/setup.py
  setup/osi_stock_move_value/odoo/addons/osi_stock_move_value
  setup/osi_stock_move_value/setup.py
Labels: bug

#431 [FIX] osi_analytic_segments: ValueError: Expected singleton: analytic.segment.one
  osi_analytic_segments/models/account_move_line.py
Labels: bug

#409 [FIX] osi_payment_method
  osi_payment_method/models/purchase.py
Labels: bug

#401 [14.0][FIX] osi_helpdesk_stock
  osi_helpdesk_stock/__manifest__.py
  osi_helpdesk_stock/models/helpdesk_ticket.py
  osi_helpdesk_stock/models/stock_request.py
  osi_helpdesk_stock/models/stock_request_order.py
Labels: bug

#382 [14.0][mig] sale_subscription_brand
  sale_subscription_brand/README.rst
  sale_subscription_brand/__init__.py
  sale_subscription_brand/__manifest__.py
  sale_subscription_brand/models/__init__.py
  sale_subscription_brand/models/sale_order.py
  sale_subscription_brand/models/sale_subscription.py
  sale_subscription_brand/static/description/icon.png
  sale_subscription_brand/views/sale_subscription_views.xml
  setup/sale_subscription_brand/odoo/addons/sale_subscription_brand
  setup/sale_subscription_brand/setup.py
Labels: migration

#434 [FIX] osi_helpdesk_stock: Conflict
  osi_helpdesk_stock/models/stock_request.py
Labels: bug

#378 [14.0][MIG] agreement_sale_subscription
  agreement_sale_subscription/README.rst
  agreement_sale_subscription/__init__.py
  agreement_sale_subscription/__manifest__.py
  agreement_sale_subscription/models/__init__.py
  agreement_sale_subscription/models/agreement.py
  agreement_sale_subscription/models/sale_order.py
  agreement_sale_subscription/models/subscription.py
  agreement_sale_subscription/static/description/icon.png
  agreement_sale_subscription/views/agreement.xml
  agreement_sale_subscription/views/subscription.xml
  setup/agreement_sale_subscription/odoo/addons/agreement_sale_subscription
  setup/agreement_sale_subscription/setup.py
Labels: needs review, migration, stale

#496 [FIX] Pre-commit errors
  agreement_sale_subscription/views/agreement.xml
  agreement_sale_subscription/views/subscription.xml
  sale_subscription_brand/views/sale_subscription_views.xml
Labels: bug
