Repository ursais/osi-addons, pull requests merged in 2023-07, with the labels that each got.

#521 [16.0][MIG] - osi_stock_move_value
  osi_stock_move_value/README.rst
  osi_stock_move_value/__init__.py
  osi_stock_move_value/__manifest__.py
  osi_stock_move_value/models/__init__.py
  osi_stock_move_value/models/stock_move.py
  osi_stock_move_value/static/description/icon.png
  osi_stock_move_value/views/stock_move_view.xml
  setup/osi_stock_move_value/odoo/addons/osi_stock_move_value
  setup/osi_stock_move_value/setup.py
Labels: migration, stale

#537 [16.0][MIG] osi_vendor_default_expense_account
  osi_vendor_default_expense_account/README.rst
  osi_vendor_default_expense_account/__init__.py
  osi_vendor_default_expense_account/__manifest__.py
  osi_vendor_default_expense_account/changes.txt
  osi_vendor_default_expense_account/models/__init__.py
  osi_vendor_default_expense_account/models/account_move.py
  osi_vendor_default_expense_account/models/res_partner.py
  osi_vendor_default_expense_account/static/description/icon.png
  osi_vendor_default_expense_account/views/res_partner_view.xml
  setup/osi_vendor_default_expense_account/odoo/addons/osi_vendor_default_expense_account
  setup/osi_vendor_default_expense_account/setup.py
Labels: migration

#539 [16.0][MIG] osi_vendor_product_return
  osi_vendor_product_return/README.rst
  osi_vendor_product_return/__init__.py
  osi_vendor_product_return/__manifest__.py
  osi_vendor_product_return/data/vendor_product_return_seq_view.xml
  osi_vendor_product_return/models/__init__.py
  osi_vendor_product_return/models/account.py
  osi_vendor_product_return/models/return_reason.py
  osi_vendor_product_return/models/stock.py
  osi_vendor_product_return/models/vendor_product_return.py
  osi_vendor_product_return/report/product_return_report.xml
  osi_vendor_product_return/report/report_productreturn.xml
  osi_vendor_product_return/security/ir.model.access.csv
  osi_vendor_product_return/security/security_view.xml
  osi_vendor_product_return/static/description/icon.png
  osi_vendor_product_return/views/account_invoice_view.xml
  osi_vendor_product_return/views/return_reason_view.xml
  osi_vendor_product_return/views/stock_view.xml
  osi_vendor_product_return/views/vendor_product_return_view.xml
  setup/osi_vendor_product_return/odoo/addons/osi_vendor_product_return
  setup/osi_vendor_product_return/setup.py
Labels: migration

#555 [ADD] account_bank_suspense_reconciliation
  account_bank_suspense_reconciliation/README.rst
  account_bank_suspense_reconciliation/__init__.py
  account_bank_suspense_reconciliation/__manifest__.py
  account_bank_suspense_reconciliation/hooks.py
  account_bank_suspense_reconciliation/models/__init__.py
  account_bank_suspense_reconciliation/models/account_bank_statement_line.py
  account_bank_suspense_reconciliation/models/account_move_line.py
  account_bank_suspense_reconciliation/static/description/icon.png
  setup/account_bank_suspense_reconciliation/odoo/addons/account_bank_suspense_reconciliation
  setup/account_bank_suspense_reconciliation/setup.py
Labels: enhancement, needs fixing
