Repository ursais/osi-addons, pull requests merged in 2023-03, with the labels that each got.

#490 [14.0][IMP] fieldservice_mobile
  fieldservice_mobile/README.rst
  fieldservice_mobile/__manifest__.py
  fieldservice_mobile/data/feature_line.xml
  fieldservice_mobile/data/feature_mapping.xml
  fieldservice_mobile/models/__init__.py
  fieldservice_mobile/models/fsm_mobile_feature_line.py
  fieldservice_mobile/models/fsm_mobile_feature_mapping.py
  fieldservice_mobile/models/ir_attachment.py
  fieldservice_mobile/security/fieldservice_mobile_security.xml
  fieldservice_mobile/security/ir.model.access.csv
  fieldservice_mobile/views/mobile_feature_line.xml
  fieldservice_mobile/views/mobile_feature_mapping.xml
Labels: bug, enhancement, needs review, stale

#530 [15.0][MIG] fieldservice_mobile: Migration to 15.0.
  fieldservice_mobile/README.rst
  fieldservice_mobile/__init__.py
  fieldservice_mobile/__manifest__.py
  fieldservice_mobile/data/base_automation.xml
  fieldservice_mobile/data/feature_line.xml
  fieldservice_mobile/data/feature_mapping.xml
  fieldservice_mobile/models/__init__.py
  fieldservice_mobile/models/fsm_mobile_feature_line.py
  fieldservice_mobile/models/fsm_mobile_feature_mapping.py
  fieldservice_mobile/models/fsm_order.py
  fieldservice_mobile/models/fsm_stage.py
  fieldservice_mobile/models/fsm_stage_history.py
  fieldservice_mobile/models/ir_attachment.py
  fieldservice_mobile/models/res_config_settings.py
  fieldservice_mobile/models/res_users.py
  fieldservice_mobile/security/fieldservice_mobile_security.xml
  fieldservice_mobile/security/ir.model.access.csv
  fieldservice_mobile/security/ir_rule.xml
  fieldservice_mobile/static/description/icon.png
  fieldservice_mobile/views/fsm_order_view.xml
  fieldservice_mobile/views/fsm_stage_view.xml
  fieldservice_mobile/views/mobile_feature_line.xml
  fieldservice_mobile/views/mobile_feature_mapping.xml
  fieldservice_mobile/views/res_config_settings.xml
Labels: needs review, migration

#501 [IMP] purchase_budget_validation: Add currency support
  purchase_budget_validation/models/crossovered_budget_lines.py
Labels: enhancement, needs review, stale
