Repository ursais/osi-addons, pull requests merged in 2024-07, with the labels that each got.

#682 [IMP] PLM Product and BOM Edit Restrictions
  ol_mrp_plm/__manifest__.py
  ol_mrp_plm/models/__init__.py
  ol_mrp_plm/models/mrp_bom.py
  ol_mrp_plm/models/plm_eco_stage.py
  ol_mrp_plm/models/product_template.py
  ol_mrp_plm/security/bom_restiction_group.xml
  ol_mrp_plm/views/mrp_eco_stage.xml
Labels: Ready for Review

#712 [17.0] [FIX] l10n_mx_edi_addenda_audi: Add fields
  l10n_mx_edi_addenda_audi/models/account_move.py
  l10n_mx_edi_addenda_audi/views/account_move.xml
  l10n_mx_edi_addenda_audi/views/l10n_mx_edi_addenda_audi.xml
Labels: enhancement

#715 [FIX] l10n_mx_edi_addenda_audi
  l10n_mx_edi_addenda_audi/models/account_move.py
  l10n_mx_edi_addenda_audi/views/account_move.xml
  l10n_mx_edi_addenda_audi/views/l10n_mx_edi_addenda_audi.xml
Labels: enhancement

#716 [FIX] l10n_mx_edi_addenda_*
  l10n_mx_edi_addenda_audi/__manifest__.py
  l10n_mx_edi_addenda_ford/__manifest__.py
  l10n_mx_edi_addenda_mabe/__manifest__.py
  l10n_mx_edi_addenda_volkswagen/__manifest__.py
  l10n_mx_edi_addenda_whirlpool/__manifest__.py
Labels: bug

#742 [FIX] l10n_mx_edi_addenda_audi
  l10n_mx_edi_addenda_audi/__manifest__.py
  l10n_mx_edi_addenda_audi/models/__init__.py
  l10n_mx_edi_addenda_audi/models/account_move.py
  l10n_mx_edi_addenda_audi/models/res_partner.py
  l10n_mx_edi_addenda_audi/views/account_move.xml
  l10n_mx_edi_addenda_audi/views/res_partner_views.xml
Labels: bug, needs review

#732 [17.0] [FIX] l10n_mx_edi_addenda_mabe
  l10n_mx_edi_addenda_mabe/views/l10n_mx_addenda_mabe_view.xml
Labels: bug, needs review

#743 [FIX] l10n_mx_edi_addenda_mabe
  l10n_mx_edi_addenda_mabe/views/l10n_mx_addenda_mabe_view.xml
Labels: bug

#744 [FIX] l10n_mx_edi_addenda*
  l10n_mx_edi_addenda_audi/__manifest__.py
  l10n_mx_edi_addenda_mabe/__manifest__.py
Labels: bug, enhancement
