Repository ursais/osi-addons, pull requests merged in 2024-08, with the labels that each got.

#782 [17.0][ADD]ol_product_configurator_stock
  ol_product_configurator_stock/__init__.py
  ol_product_configurator_stock/__manifest__.py
  ol_product_configurator_stock/models/__init__.py
  ol_product_configurator_stock/models/product_attribute.py
  ol_product_configurator_stock/static/description/icon.png
  ol_product_configurator_stock/tests/__init__.py
  ol_product_configurator_stock/tests/test_product_confi_stock.py
Labels: enhancement

#788 [IMP]ol_mrp_sale_price_rollup
  ol_mrp_sale_price_rollup/report/mrp_report_bom_structure.py
Labels: bug

#791 [FIX] l10n_mx_edi_addenda_mabe: Fix currency rate
  l10n_mx_edi_addenda_mabe/views/l10n_mx_addenda_mabe_view.xml
  l10n_mx_edi_addenda_volkswagen/views/l10n_mx_edi_addenda_volkswagen.xml
Labels: needs review

#793 [IMP] l10n_mx_edi_addenda*
  l10n_mx_edi_addenda_mabe/__manifest__.py
  l10n_mx_edi_addenda_volkswagen/__manifest__.py
Labels: enhancement

#818 [FIX]ol_mrp_sale_price_rollup
  ol_mrp_sale_price_rollup/models/product_config.py
  ol_mrp_sale_price_rollup/models/product_product.py
  ol_mrp_sale_price_rollup/models/product_template.py
  ol_mrp_sale_price_rollup/static/src/components/bom_overview/mrp_bom_overview_table.xml
  ol_mrp_sale_price_rollup/views/product_view.xml
Labels: bug

#829 [17.0][MIG] documents_mrp
  documents_mrp/README.rst
  documents_mrp/__init__.py
  documents_mrp/__manifest__.py
  documents_mrp/data/documents_facet.xml
  documents_mrp/data/documents_folder.xml
  documents_mrp/data/documents_tag.xml
  documents_mrp/data/res_company.xml
  documents_mrp/models/__init__.py
  documents_mrp/models/mrp_production.py
  documents_mrp/models/res_company.py
  documents_mrp/models/res_config_settings.py
  documents_mrp/static/description/icon.png
  documents_mrp/views/res_config_settings.xml
Labels: enhancement

#830 [17.0][MIG] documents_purchase
  documents_purchase/README.rst
  documents_purchase/__init__.py
  documents_purchase/__manifest__.py
  documents_purchase/data/documents_facet.xml
  documents_purchase/data/documents_folder.xml
  documents_purchase/data/documents_tag.xml
  documents_purchase/data/res_company.xml
  documents_purchase/models/__init__.py
  documents_purchase/models/purchase_order.py
  documents_purchase/models/res_company.py
  documents_purchase/models/res_config_settings.py
  documents_purchase/static/description/icon.png
  documents_purchase/views/res_config_settings.xml
Labels: enhancement

#831 [17.0][MIG] documents_quality
  documents_quality/README.rst
  documents_quality/__init__.py
  documents_quality/__manifest__.py
  documents_quality/data/documents_facet.xml
  documents_quality/data/documents_folder.xml
  documents_quality/data/documents_tag.xml
  documents_quality/data/res_company.xml
  documents_quality/models/__init__.py
  documents_quality/models/quality_alert.py
  documents_quality/models/quality_check.py
  documents_quality/models/quality_point.py
  documents_quality/models/res_company.py
  documents_quality/models/res_config_settings.py
  documents_quality/static/description/icon.png
  documents_quality/views/res_config_settings.xml
Labels: enhancement

#832 [17.0][MIG] documents_stock_lot
  documents_stock_lot/README.rst
  documents_stock_lot/__init__.py
  documents_stock_lot/__manifest__.py
  documents_stock_lot/data/documents_facet.xml
  documents_stock_lot/data/documents_folder.xml
  documents_stock_lot/data/documents_tag.xml
  documents_stock_lot/data/documents_workflow_rule.xml
  documents_stock_lot/data/res_company.xml
  documents_stock_lot/models/__init__.py
  documents_stock_lot/models/documents_workflow_rule.py
  documents_stock_lot/models/res_company.py
  documents_stock_lot/models/res_config_settings.py
  documents_stock_lot/models/stock_lot.py
  documents_stock_lot/security/ir.model.access.csv
  documents_stock_lot/static/description/icon.png
  documents_stock_lot/views/res_config_settings.xml
  documents_stock_lot/wizards/__init__.py
  documents_stock_lot/wizards/select_lot.py
  documents_stock_lot/wizards/select_lot_view.xml
Labels: enhancement

#833 [17.0][MIG] documents_partner
  documents_partner/README.rst
  documents_partner/__init__.py
  documents_partner/__manifest__.py
  documents_partner/data/documents_facet.xml
  documents_partner/data/documents_folder.xml
  documents_partner/data/documents_tag.xml
  documents_partner/data/res_company.xml
  documents_partner/models/__init__.py
  documents_partner/models/res_company.py
  documents_partner/models/res_config_settings.py
  documents_partner/models/res_partner.py
  documents_partner/static/description/icon.png
  documents_partner/views/res_config_settings.xml
Labels: enhancement
