Repository ursais/osi-addons, pull requests merged in 2024-06, with the labels that each got.

#630 [FIX] .pre-commit-config.yaml
  .copier-answers.yml
  .flake8
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  advance_check_void/data/payment_methods_data.xml
  advance_check_void/views/account_payment_view.xml
  advance_check_void/wizard/account_move_reversal_view.xml
  osi_fifo_serialized_fix/models/mrp_production.py
  osi_fifo_serialized_fix/models/mrp_workcenter_productivity.py
  osi_fifo_serialized_fix/models/stock_valuation_layer.py
Labels: bug, needs review

#627 [ADD] l10n_mx_edi_addenda_audi
  __init__.py
  l10n_mx_edi_addenda_audi/__init__.py
  l10n_mx_edi_addenda_audi/__manifest__.py
  l10n_mx_edi_addenda_audi/models/__init__.py
  l10n_mx_edi_addenda_audi/models/account_move.py
  l10n_mx_edi_addenda_audi/views/account_move_views.xml
  l10n_mx_edi_addenda_audi/views/l10n_mx_edi_addenda_audi_view.xml
Labels: enhancement, needs review

#624 [ADD] l10n_mx_edi_addenda_whirlpool
  l10n_mx_edi_addenda_whirlpool/README.rst
  l10n_mx_edi_addenda_whirlpool/__init__.py
  l10n_mx_edi_addenda_whirlpool/__manifest__.py
  l10n_mx_edi_addenda_whirlpool/views/l10n_mx_addenda_whirlpool_view.xml
Labels: enhancement, needs review

#631 [IMP] added ol_purchase_last_price_info module for the update last pu…
  ol_purchase_last_price_info/README.md
  ol_purchase_last_price_info/__init__.py
  ol_purchase_last_price_info/__manifest__.py
  ol_purchase_last_price_info/models/__init__.py
  ol_purchase_last_price_info/models/product.py
  ol_purchase_last_price_info/static/description/icon.png
  ol_purchase_last_price_info/views/product_product_view.xml
Labels: enhancement

#636 [ADD][17.0]ol_product_ship_multiplier
  ol_product_ship_multiplier/__init__.py
  ol_product_ship_multiplier/__manifest__.py
  ol_product_ship_multiplier/models/__init__.py
  ol_product_ship_multiplier/models/delivery_carrier_multiplier.py
  ol_product_ship_multiplier/models/product_template.py
  ol_product_ship_multiplier/security/ir.model.access.csv
  ol_product_ship_multiplier/security/security.xml
  ol_product_ship_multiplier/static/description/icon.png
  ol_product_ship_multiplier/tests/__init__.py
  ol_product_ship_multiplier/tests/test_ol_product_ship_multiplier.py
  ol_product_ship_multiplier/views/delivery_carrier_multiplier_views.xml
  ol_product_ship_multiplier/views/product_views.xml
Labels: enhancement

#623 [ADD] l10n_mx_edi_addenda_mabe
  l10n_mx_edi_addenda_mabe/README.rst
  l10n_mx_edi_addenda_mabe/__init__.py
  l10n_mx_edi_addenda_mabe/__manifest__.py
  l10n_mx_edi_addenda_mabe/i18n/es_MX.po
  l10n_mx_edi_addenda_mabe/i18n/l10n_mx_edi_addenda_mabe.pot
  l10n_mx_edi_addenda_mabe/models/__init__.py
  l10n_mx_edi_addenda_mabe/models/account_move.py
  l10n_mx_edi_addenda_mabe/models/res_partner.py
  l10n_mx_edi_addenda_mabe/views/account_move_views.xml
  l10n_mx_edi_addenda_mabe/views/l10n_mx_addenda_mabe_view.xml
  l10n_mx_edi_addenda_mabe/views/res_partner_views.xml
Labels: enhancement, needs review

#634 [FIX] l10n_mx_edi_addenda_audi
  l10n_mx_edi_addenda_audi/README.rst
  l10n_mx_edi_addenda_audi/__manifest__.py
  l10n_mx_edi_addenda_audi/i18n/es_MX.po
  l10n_mx_edi_addenda_audi/i18n/l10n_mx_edi_addenda_audi.pot
  l10n_mx_edi_addenda_audi/models/__init__.py
  l10n_mx_edi_addenda_audi/models/account_move.py
  l10n_mx_edi_addenda_audi/models/account_move_line.py
  l10n_mx_edi_addenda_audi/models/product_product.py
  l10n_mx_edi_addenda_audi/models/product_template.py
  l10n_mx_edi_addenda_audi/views/account_move_views.xml
  l10n_mx_edi_addenda_audi/views/l10n_mx_edi_addenda_audi_view.xml
  l10n_mx_edi_addenda_audi/views/product_template_views.xml
Labels: bug, needs review

#625 [ADD] l10n_mx_edi_addenda_ford
  l10n_mx_edi_addenda_ford/README.rst
  l10n_mx_edi_addenda_ford/__init__.py
  l10n_mx_edi_addenda_ford/__manifest__.py
  l10n_mx_edi_addenda_ford/i18n/es_MX.po
  l10n_mx_edi_addenda_ford/i18n/l10n_mx_edi_addenda_ford.pot
  l10n_mx_edi_addenda_ford/models/__init__.py
  l10n_mx_edi_addenda_ford/models/account_move.py
  l10n_mx_edi_addenda_ford/views/account_move_views.xml
  l10n_mx_edi_addenda_ford/views/l10n_mx_addenda_ford_view.xml
Labels: enhancement, needs review

#626 [ADD] l10n_mx_edi_addenda_volkswagen
  l10n_mx_edi_addenda_audi/__init__.py
  l10n_mx_edi_addenda_volkswagen/README.rst
  l10n_mx_edi_addenda_volkswagen/__init__.py
  l10n_mx_edi_addenda_volkswagen/__manifest__.py
  l10n_mx_edi_addenda_volkswagen/i18n/es_MX.po
  l10n_mx_edi_addenda_volkswagen/i18n/l10n_mx_edi_addenda_volkswagen.pot
  l10n_mx_edi_addenda_volkswagen/models/__init__.py
  l10n_mx_edi_addenda_volkswagen/models/account_move.py
  l10n_mx_edi_addenda_volkswagen/views/account_move_views.xml
  l10n_mx_edi_addenda_volkswagen/views/l10n_mx_edi_addenda_volkswagen_views.xml
Labels: enhancement, needs review

#641 [FIX] l10n_mx_edi_addenda_audi
  l10n_mx_edi_addenda_audi/__manifest__.py
  l10n_mx_edi_addenda_audi/models/__init__.py
  l10n_mx_edi_addenda_audi/models/account_move_line.py
  l10n_mx_edi_addenda_audi/models/product_product.py
  l10n_mx_edi_addenda_audi/models/product_template.py
  l10n_mx_edi_addenda_audi/static/description/icon.png
  l10n_mx_edi_addenda_audi/views/account_move.xml
  l10n_mx_edi_addenda_audi/views/l10n_mx_edi_addenda_audi.xml
  l10n_mx_edi_addenda_audi/views/product_template.xml
Labels: bug, needs review

#642 [FIX] l10n_mx_edi_addenda_audi
  l10n_mx_edi_addenda_audi/README.rst
  l10n_mx_edi_addenda_audi/__init__.py
  l10n_mx_edi_addenda_audi/views/account_move.xml
Labels: bug

#660 [IMP] added ol_tier_validation module for restrictions and tracking
  ol_tier_validation/README.rst
  ol_tier_validation/__init__.py
  ol_tier_validation/__manifest__.py
  ol_tier_validation/models/__init__.py
  ol_tier_validation/models/tier_definition.py
  ol_tier_validation/security/tier_validation_group.xml
  ol_tier_validation/static/description/icon.png
  ol_tier_validation/tests/__init__.py
  ol_tier_validation/tests/test_tier_validation.py
  ol_tier_validation/views/tier_definition_view.xml
Labels: Ready for Review

#657 [WIP] ol_mrp_plm_cancel module
  ol_mrp_plm_cancel/__init__.py
  ol_mrp_plm_cancel/__manifest__.py
  ol_mrp_plm_cancel/models/__init__.py
  ol_mrp_plm_cancel/models/mrp_eco.py
  ol_mrp_plm_cancel/models/plm_eco_stage.py
  ol_mrp_plm_cancel/static/description/icon.png
  ol_mrp_plm_cancel/tests/__init__.py
  ol_mrp_plm_cancel/tests/test_ol_mrp_plm.py
  ol_mrp_plm_cancel/views/mrp_eco_stage.xml
  ol_mrp_plm_cancel/views/mrp_eco_view.xml
Labels: Ready for Review

#662 [FIX] installation of ol_mrp_plm_cancel module gives error
  ol_mrp_plm_cancel/models/mrp_eco.py
Labels: Ready for Review

#664 [IMP] add ol_product_state module for restric product state
  ol_product_state/README.rst
  ol_product_state/__init__.py
  ol_product_state/__manifest__.py
  ol_product_state/models/__init__.py
  ol_product_state/models/product_template.py
  ol_product_state/security/product_state_group.xml
  ol_product_state/static/description/icon.png
  ol_product_state/views/product_template_view.xml
Labels: Ready for Review
