Repository ursais/osi-addons, pull requests merged in 2025-05, with the labels that each got.

#1330 [IMP]ol_stock_constrained_availability
  ol_stock_constrained_availability/models/mrp_production.py
  ol_stock_constrained_availability/models/sale_order.py
Labels: bug

#1294 [IMP] ol_sale_booking (New Line Fields)
  ol_sale_booking/models/sale_booking.py
  ol_sale_booking/models/sale_booking_line.py
  ol_sale_booking/views/sale_booking_views.xml
  ol_sale_booking/views/sale_order_views.xml
Labels: work in progress

#1352 [IMP]ol_stock_loadcsv
  ol_stock_loadcsv/wizard/csv_loader_wizard.py
Labels: bug

#1365 [IMP] mrp_repair_component_history (Add Button for Existing Serials)
  mrp_repair_component_history/models/component_history.py
  mrp_repair_component_history/models/repair_order.py
  mrp_repair_component_history/models/stock_lot.py
  mrp_repair_component_history/tests/__init__.py
  mrp_repair_component_history/tests/test_mrp_repair_component_history.py
  mrp_repair_component_history/views/component_history_views.xml
  mrp_repair_component_history/views/repair_views.xml
  mrp_repair_component_history/views/stock_lot_views.xml
Labels: work in progress

#1363 [IMP]ADD Unit Testcase.
  ol_sale_booking/tests/test_sale_booking.py
Labels: work in progress

#1374 [IMP]Added IR Defaults in data.
  ol_stock/data/stock_location_data.xml
Labels: enhancement
