Repository ursais/osi-addons, pull requests merged in 2025-09, with the labels that each got.

#1632 [FIX]ol_credit_limit
  ol_credit_limit/README.rst
  ol_credit_limit/data/credit_limit_data.xml
  ol_credit_limit/data/exception_config_data.xml
  ol_credit_limit/data/function.xml
  ol_credit_limit/models/account_move.py
  ol_credit_limit/models/mrp.py
  ol_credit_limit/models/res_partner.py
  ol_credit_limit/models/sale_order.py
  ol_credit_limit/models/stock_picking.py
  ol_credit_limit/tests/test_ol_credit_limit.py
  ol_credit_limit/views/mrp_production_view.xml
  ol_credit_limit/views/res_partner.xml
  ol_credit_limit/views/sale_order_view.xml
  ol_credit_limit/views/stock_picking_view.xml
Labels: bug

#1596 [ADD] Future Effective Date on Price Reviews
  ol_product_pricing_review/__manifest__.py
  ol_product_pricing_review/data/ir_cron.xml
  ol_product_pricing_review/models/product_price_review.py
  ol_product_pricing_review/tests/test_ol_product_pricing_review.py
  ol_product_pricing_review/views/product_price_review_views.xml
Labels: enhancement

#1627 [IMP]AP/AR/Follow-up mapped to contacts on customer.
  ol_account/__manifest__.py
  ol_account/models/__init__.py
  ol_account/models/account_batch_payment.py
  ol_account/models/account_move.py
  ol_account/models/res_partner.py
  ol_account/views/res_partner_view.xml
  ol_account/wizard/__init__.py
  ol_account/wizard/account_move_send.py
  ol_account/wizard/followup_manual_reminder.py
  ol_base/models/res_partner.py
  ol_base/views/res_partner.xml
Labels: enhancement, Ready for Review
