Repository ursais/osi-addons, pull requests merged in 2025-08, with the labels that each got.

#1537 [FIX]Bug: Blocking Error when configuring an existing variant (#64376)
  product_configurator_mrp_quantity/models/product_attribute.py
Labels: bug

#1512 [IMP]Customization to allow the functionality to set defaults per company
  ol_product_configurator/models/attribute_value.py
  ol_product_configurator/models/product_template_attribute_line.py
  ol_product_configurator/views/product_template_views.xml
Labels: enhancement

#1525 [IMP]OL-Account.
  ol_account/__manifest__.py
  ol_account/data/server_action.xml
  ol_account/views/account_invoice.xml
Labels: enhancement

#1538 [FIX]Ticket #63845
  ol_sale/models/sale_order.py
Labels: enhancement

#1548 [ADD] Added outstanding receivable field on partner : compute total due including rollup partners
  ol_credit_limit/models/res_partner.py
  ol_credit_limit/views/res_partner.xml
Labels: Ready for Review
